apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-adapter-secrets
  labels:
    app: whatsapp-adapter
    component: backend
    service: messaging
type: Opaque
stringData:
  twilio-account-sid: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  twilio-auth-token: "your_twilio_auth_token_here"
  twilio-phone-number: "+14155238886"
  database-url: "postgres://username:password@postgresql:5432/re9ai_dev"
---
apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-adapter-secrets-template
  labels:
    app: whatsapp-adapter
    component: backend
    service: messaging
  annotations:
    template: "true"
    description: "Template for WhatsApp adapter secrets - replace values before applying"
type: Opaque
stringData:
  twilio-account-sid: "REPLACE_WITH_YOUR_TWILIO_ACCOUNT_SID"
  twilio-auth-token: "REPLACE_WITH_YOUR_TWILIO_AUTH_TOKEN"
  twilio-phone-number: "REPLACE_WITH_YOUR_TWILIO_PHONE_NUMBER"
  database-url: "REPLACE_WITH_YOUR_DATABASE_URL"
